using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="Vector3TestsTest.AbsOfVector000Is0Test.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace RP.Math.Tests
{
    public partial class Vector3TestsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(Vector3TestsTest))]
public void AbsOfVector000Is0Test345()
{
    Vector3Tests s0 = new Vector3Tests();
    this.AbsOfVector000Is0Test(s0);
    Assert.IsNotNull((object)s0);
}
    }
}
